### ISSUE TITLE
For the animal pictures create slideshow buttons. So that if you are looking at an animal your choices are:  <  Back  >

### ISSUE THREAD

**Issue by wadek2** [ExtraLudic/DaedalusLabrynthV2#15]

**Comment by esalling23** [comment]
Should these go infinitely or cut off at the beginning/end? (ie the last elephant will only have a < button not a > button because its the last one) @wadek2

**Comment by esalling23** [comment]
this is done, infinitely for now but it's easy to remove the next or back buttons from the first and last image
