### ISSUE TITLE
Correct sequence does not trigger globes.

### ISSUE THREAD

**Issue by CivicSam** [ExtraLudic/DaedalusLabrynthV2#17]
Sequence Red Red Gray Red Gray Gray is supposed to trigger the Globes. Instead nothing happens.

**Comment by esalling23** [comment]
I am able to trigger the "take_an_orb" script after entering this button code 
<img width="427" alt="screen shot 2018-02-22 at 11 18 28 am" src="https://user-images.githubusercontent.com/11821504/36550029-394d65f0-17c2-11e8-963a-9b53a0f447c7.png">

<img width="623" alt="screen shot 2018-02-22 at 11 17 58 am" src="https://user-images.githubusercontent.com/11821504/36549956-101f542c-17c2-11e8-9324-dac9ebff4fcc.png">

**Comment by esalling23** [comment]
@wadek2 just noticed it's out of order in the code, fixing now

**Comment by esalling23** [comment]
tested with the following code works
<img width="406" alt="screen shot 2018-02-22 at 11 22 09 am" src="https://user-images.githubusercontent.com/11821504/36550173-a79ca480-17c2-11e8-87eb-8fd71e12cf5e.png">
