### ISSUE TITLE
Onboarding Needs

### ISSUE THREAD

**Issue by esalling23** [ExtraLudic/DaedalusLabrynthV2#20]
We want a message to (each?) player with a button that will have them start - this will trigger input_nodes_1

@wadek2 @CivicSam is there anything else we want from this onboarding?

**Comment by CivicSam** [comment]
I don't believe so. The puzzles and interface should be self explanatory and simple to use. And we may have videos to explain certain things. Don't add anything to the onboarding yet, but we will be watching testers to see what confuses them, and we may ask for more onboarding features or copy later. @esalling23
