### ISSUE TITLE
logical problem for updating players on events like button presses (orbs ex)

### ISSUE THREAD

**Issue by esalling23** [ExtraLudic/DaedalusLabrynthV2#36]

**Comment by esalling23** [comment]
ideas for this: channel with bot updates and buttons that would trigger a new card in the direct message channel to place players in that updated state

**Comment by esalling23** [comment]
we could also have a system in which, if a player entered a repeat code, it just sent them to the "correct" message but added some text like "someone already entered that, here you go!" instead of "someone entered a correct button sequence"

**Comment by CivicSam** [comment]
That's pretty clean. Or 

"You entered a correct code! (You are the Nth player on your team to enter this code. Have you been communicating with your team?)"

**Comment by esalling23** [comment]
is it important for the data team to know how many times players are entering correct codes? @CivicSam

**Comment by CivicSam** [comment]
Almost definitely, why?

**Comment by esalling23** [comment]
okay, just checking! we are tracking that already so shouldnt be difficult

**Comment by esalling23** [comment]
For now: 
show repeat message with a recap attachment of the corresponding correct sequence message

**Comment by esalling23** [comment]
@wadek2 @CivicSam how does this look?
<img width="640" alt="screen shot 2018-03-08 at 2 02 54 pm" src="https://user-images.githubusercontent.com/11821504/37170669-7b1d1b2a-22d9-11e8-9b65-33e40f1bb656.png">
