### ISSUE TITLE
Text on "few dots" should change after the plaque falls.

### ISSUE THREAD

**Issue by CivicSam** [ExtraLudic/DaedalusLabrynthV2#4]
After the plaque falls, add this line of text to the small dots painting description.

"Hey, the plaque is gone! It must have fallen off the wall."

**Comment by esalling23** [comment]
@wadek2 should this be combined with the hole state? for example, if you have triggered the hole and the plaque to fall, what should the text be for the few dots painting?

**Comment by CivicSam** [comment]
Good point. The plaque should remain on the floor forever once it's there, even if it's a hole.I just changed the text in the doc to reflect this. They must be able to access the plaque.
