### ISSUE TITLE
Hole appearing when it shouldn't

### ISSUE THREAD

**Issue by anikaolivo** [ExtraLudic/DaedalusLabrynthV2#61]
- Input combo 3 (grey green grey grey grey grey)
- Input combo 0 (grey red green grey green red), still switched to plaque falling off wall
- Input combo 4 (red red grey red grey grey)
- Input combo 1 (grey green red grey red green), still switched to unlocking safari video
- Main room state is still correct and the hole is NOT there, but the few dots area state is changed to the hole state and has the documents available
- When inputting the hole code (green red red red grey green) after this, it does not say it was already used

This also happened when I used these button combo orders:
- 1, 0, 3
- 1, 3
- 3, 1

Therefore, looks like it happens when combos 1 and 3 are both done before combo 2.

**Comment by esalling23** [comment]
this should be fixed if you put in the safari and glyph and then random/orb
